name = "AnamnesisAnalytics"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Hyperpolymath"]
version = "0.1.0"

[deps]
Serd = "f22d1e7e-8670-4d9f-a774-e72e57e1b91f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
ReservoirComputing = "6e605b0a-d992-4a46-baa5-d0fa79e0e369"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.10"
